import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../../globals.css";

import { AppSidebar } from '@/components/app-sidebar'
import { SiteHeader } from '@/components/site-header'
import {
    SidebarInset,
    SidebarProvider,
} from '@/components/ui/sidebar'
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";

const geistSans = localFont({
    src: "../../../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

const geistMono = localFont({
    src: "../../../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const { session } = await getUser()

    if (!session) {
        return redirect("/dashboard/sign-in")
    }

    return (
        <div className={`${geistSans.variable} ${geistMono.variable}`}>
            <SidebarProvider
                style={
                    {
                        "--sidebar-width": "18rem",
                        "--header-height": "3rem",
                    } as React.CSSProperties
                }
            >
                <AppSidebar variant="inset" />
                <SidebarInset>
                    <SiteHeader />
                    <div className="flex flex-1 flex-col py-4 md:py-6 lg:py-8 px-4 lg:px-6 xl:px-8">
                        {children}
                    </div>
                </SidebarInset>
            </SidebarProvider>
        </div>
    );
}
